export { default as AdminSignin } from "./auth/AdminSignin.jsx";
export { default as StudentSignin } from "./auth/StudentSignin.jsx";
export { default as TeacherSignin } from "./auth/TeacherSignin.jsx";
export { default as Home } from "./common/Home";
export { default as AdminDashboard } from "./dashboard/admin/AdminDashboard.jsx";
export { default as Assignments } from "./dashboard/admin/Assignments.jsx";
export { default as Attendance } from "./dashboard/admin/Attendance.jsx";
export { default as Classes } from "./dashboard/admin/Classes.jsx";
export { default as EventCalender } from "./dashboard/admin/EventCalender.jsx";
export { default as Exam } from "./dashboard/admin/Exam.jsx";
export { default as Library } from "./dashboard/admin/Library.jsx";
export { default as Performance } from "./dashboard/admin/Performance.jsx";
export { default as SettingsProfile } from "./dashboard/admin/SettingsProfile.jsx";
export { default as Students } from "./dashboard/admin/Students.jsx";
export { default as Teachers } from "./dashboard/admin/Teachers.jsx";
export { default as Announcement } from "./dashboard/admin/Anountcement.jsx";
export { default as StudentDashboard } from "./dashboard/StudentDashboard.jsx";
export { default as TeacherDashboard } from "./dashboard/TeacherDashboard.jsx";

